# display
CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y //default
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_LV_Z_VDB_SIZE=64
CONFIG_LV_DPI_DEF=148
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_LV_COLOR_DEPTH_1=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_COMPILER_OPT="-DZMK_SPLIT_BLE_PERIPHERAL_COUNT=2"

CONFIG_ZMK_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=y
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=y
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="center"
  # default, or "center", "right"
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_NAME_SCROLL_WIDTH=75
  # default is 50 pixels
# CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
CONFIG_ZMK_HID_INDICATORS=n
# 60sec
CONFIG_ZMK_IDLE_TIMEOUT=60000
